export { Lab } from './lab.entity';
export { Department } from './department.entity';
export { SampleType } from './sample-type.entity';
export { User } from './user.entity';
export { RefreshToken } from './refresh-token.entity';
export { TestCatalog } from './test-catalog.entity';
export { TestParameter } from './test-parameter.entity';
export { Doctor } from './doctor.entity';
export { Patient } from './patient.entity';
export { Booking, BookingStatus } from './booking.entity';
export { BookingTest } from './booking-test.entity';
