import { buildBookingPersistenceData } from '../utils/booking-persistence.util';

describe('buildBookingPersistenceData', () => {
  it('maps legacy booking payload fields into booking persistence columns', () => {
    const payload = {
      patientId: '81103f57-4e14-4603-b5bb-6566f23af2ee',
      testIds: ['124', '554', '558'],
      preferredDate: '2026-07-20',
      notes: 'Demo booking prefilled from mock values',
      email: 'aarav@example.com',
      phone: '9876543210',
      paymentMode: 'CASH',
      amount: 680,
      centre: 'MAIN',
      regNo: 'REG-1001',
      barcode: 'BC-1001',
      time: '10:30',
      recordNo: 'REC-001',
      uid: 'UID-001',
      patientName: 'Aarav Sharma',
      patientTitle: 'Mr.',
      age: 32,
      ageUnit: 'Year',
      sex: 'Male',
      mobile: '9876543210',
      area: 'Sector 15, Noida',
      doctor: 'DR001',
      doctorEmail: 'drsharma@example.com',
      doctorType: 'Consultant',
      bookingType: 'Routine',
      sample: 'BLOOD',
      takenBy: 'Lab Tech 1',
      panel: 'BP001',
      fileNo: 'FILE-001',
      userRate: 'standard',
      resultType: 'Normal',
      tests: [
        {
          id: 'mock-test-1',
          backendId: '124',
          code: 'O32U',
          test: '24 HRS.URINE CREATININE',
          reportDays: 1,
          rate: 150,
        },
        {
          id: 'test-1784558062922',
          backendId: '554',
          code: '24CRT',
          test: '24 HRS.URINARY CREATININE',
          reportDays: 1,
          rate: 300,
        },
        {
          id: 'test-1784558062922',
          backendId: '558',
          code: '24HRSK',
          test: '24 HRS.URINARY POTASSIUM(K)',
          reportDays: 1,
          rate: 400,
        },
      ],
      moveAllColumns: false,
      bookingPlusResult: true,
      bookingPlusReceipt: false,
      printWorkingSlip: true,
      extraBy: 'doctor',
      discountBy: 'percentage',
      payType: 'Cash',
      discount: 170,
      discountPercent: 20,
      total: 850,
      net: 680,
      paid: 680,
      cancelRemark: 'Demo booking prefilled from mock values',
    } as any;

    const booking = buildBookingPersistenceData(payload, 'BOOK-1001', 'user-123');

    expect(booking).toMatchObject({
      bookingNumber: 'BOOK-1001',
      patientId: payload.patientId,
      status: 'Pending',
      notes: payload.notes,
      email: payload.email,
      phone: payload.phone,
      paymentMode: 'CASH',
      amount: 680,
      centre: 'MAIN',
      regNo: 'REG-1001',
      barcode: 'BC-1001',
      bookingTime: '10:30',
      recordNo: 'REC-001',
      uid: 'UID-001',
      patientName: 'Aarav Sharma',
      patientTitle: 'Mr.',
      age: 32,
      ageUnit: 'Year',
      sex: 'Male',
      mobile: '9876543210',
      area: 'Sector 15, Noida',
      doctorPrintName: 'DR001',
      doctorEmail: 'drsharma@example.com',
      doctorType: 'Consultant',
      bookingType: 'Routine',
      sample: 'BLOOD',
      takenBy: 'Lab Tech 1',
      panel: 'BP001',
      fileNo: 'FILE-001',
      userRate: 'standard',
      resultType: 'Normal',
      moveAllColumns: false,
      bookingPlusResult: true,
      bookingPlusReceipt: false,
      printWorkingSlip: true,
      extraBy: 'doctor',
      discountBy: 'percentage',
      discount: 170,
      discountPercent: 20,
      totalAmount: 850,
      net: 680,
      paid: 680,
      cancellationRemark: payload.cancelRemark,
      createdBy: 'user-123',
      updatedBy: 'user-123',
    });

    expect(booking.preferredDate).toEqual(new Date('2026-07-20'));
    expect(booking.bookingDate).toEqual(new Date('2026-07-20'));
  });
});
